Ext.define('Testpro.testpro.shared.com.model.airlineboundedcontext.reservedomain.FlightModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "flightId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "flightName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "totalSeat",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "flysource",
          "reference": "City",
          "defaultValue": ""
     }, {
          "name": "flydestination",
          "reference": "City",
          "defaultValue": ""
     }, {
          "name": "departureDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "departureTime",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "fareEconomy",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "fareFirst",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "bookEcon",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "bookFirst",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});