Ext.define('Testpro.testpro.shared.com.model.appinsight.health.BEntityModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "bid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bNm",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bno",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "cDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "CEntity",
          "reference": "CEntityModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});